//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agents()
        {
            this.Productsale = new HashSet<Productsale>();
        }
    
        public string LogoMain { get
            {
                return "/Resources" + Logo;
            } }
        public int Id { get; set; }
        public string TypeAgent { get; set; }
        public string NameAgent { get; set; }
        public string EmailAgent { get; set; }
        public string Telephone { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public string Priority { get; set; }
        public string Derector { get; set; }
        public Nullable<double> INN { get; set; }
        public Nullable<double> KPP { get; set; }
        public Nullable<int> IdManager { get; set; }
    
        public virtual Manager Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productsale> Productsale { get; set; }
    }
}
