//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Epmloyees
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Passport { get; set; }
        public string BankData { get; set; }
        public int IdProduction { get; set; }
        public Nullable<bool> Family { get; set; }
        public Nullable<bool> Health { get; set; }
        public int IdManager { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Production Production { get; set; }
    }
}
