//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string SomePost { get; set; }
        public Nullable<int> Count { get; set; }
        public string Numeric { get; set; }
        public Nullable<int> CountOnBase { get; set; }
        public Nullable<int> MinCount { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual HistoryOfPost HistoryOfPost { get; set; }
    }
}
