//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productsale
    {
        public int IdAgent { get; set; }
        public int IdПродукта { get; set; }
        public string Продукция { get; set; }
        public string NameAgent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CountProducts { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual Product_short Product_short { get; set; }
    }
}
