//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_short
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_short()
        {
            this.Productsale = new HashSet<Productsale>();
        }
    
        public int IdProduct { get; set; }
        public string NameOfProduct { get; set; }
        public string Type { get; set; }
        public Nullable<double> Artikul { get; set; }
        public Nullable<int> CountHumanForSale { get; set; }
        public Nullable<int> NomerEnviriment { get; set; }
        public Nullable<decimal> MinPriceForAgent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productsale> Productsale { get; set; }
    }
}
