//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string INN { get; set; }
        public string Type { get; set; }
        public int IdPost { get; set; }
        public int IdManager { get; set; }
    
        public virtual HistoryOfPost HistoryOfPost { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
